config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders do
    collection do
      put :label
    end
  end
  devise_for :users
  get 'summary' => 'order_items#summary'
  get 'mailing' => 'orders#mailing'
  root 'orders#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :order_items, allow_destroy: true
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :order_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @order_items = current_user.order_items.order("order_id DESC, id ASC").all
  end

  def summary
    if params[:start_date].nil?
      flash.now[:alert] = "Please enter start date and end date to summarise"
    else
      bom = DateTime::civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i,params[:start_date][:day].to_i)
      eom = DateTime::civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i,params[:end_date][:day].to_i)
      @orders = current_user.orders.where(:date_received => bom.beginning_of_day..eom.end_of_day).ids
      if @orders.empty?
        flash.now[:alert] = "There are no records for the date range specified"
      end
      @order_items = current_user.order_items.where(:order_id => @orders).group(:description).sum(:quantity)
    end
  end
  
  def new
    @order_item = current_user.order_items.build
  end

  def edit
  end

  def create
    @order_item = current_user.order_items.build(order_item_params)

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to order_items_path, notice: 'Order item was successfully created.' }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to order_items_path, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = current_user.order_items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:description, :item_number, :unit_price, :quantity, :order_id, :user_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'label_layout', :only => [:label]

  def label
    @orders = current_user.orders.find(params[:order_ids])
  end
 
  def mailing
     @mailing = current_user.orders.find_by_sql(
       ["select shipping_name, paypal_email, shipping_address3, shipping_address4, shipping_address5, sum(order_items.quantity) quantity 
       from orders 
       join order_items on orders.id = order_items.order_id 
       where order_items.user_id = ? 
       group by orders.paypal_email, orders.shipping_name, orders.shipping_address5, orders.shipping_address4, orders.shipping_address3",current_user.id])
  end
 
  def index
    @orders = current_user.orders.order("id DESC").all
  end

  def new
    @order = current_user.orders.build
  end

  def edit
  end

  def create

    @order = current_user.orders.build(order_params)

    respond_to do |format|
      if params[:paypal_button] || !@order.save
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :index, status: :created, location: @order }
      end
    end
  end

  def update

    respond_to do |format|
      if current_user.order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
        format.json { render :index, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = current_user.orders.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(
        :transaction_id, 
        :paypal_id, 
        :paypal_email, 
        :date_received, 
        :shipping_name, 
        :shipping_address1, 
        :shipping_address2, 
        :shipping_address3, 
        :shipping_address4, 
        :shipping_address5, 
        :payment_total, 
        :payment_subtotal, 
        :shipping_total, 
        :user_id, 
        order_items_attributes: [:id, :description, :item_number, :unit_price, :quantity, :order_id, :user_id] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "PAYPAL", root_path, id: "logo" %>
    </div>
    
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Orders", orders_path %></li>
        <li><%= link_to "Items", order_items_path %></li>
        <li><%= link_to "Summary", summary_path %></li>
        <li><%= link_to "Mailing", mailing_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %> </li>
        <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %> </li> |
            <li><%= link_to "Login", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
      <%= yield %>
    </div>

</body>
</html>

app/views/layouts/label_layout.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Workspace</title>
    <%= stylesheet_link_tag    'label', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
</body>
</html>

app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"><%= f.label :order_id %><%= f.collection_select :order_id, current_user.orders.all, :id, :id %></div><br>
  <div class="field"><%= f.label 'Item' %><%= f.text_field :id, disabled: true %></div>
  <div class="field"><%= f.label :description %><%= f.text_field :description %></div>
  <div class="field"><%= f.label :item_number %><%= f.text_field :item_number %></div>
  <div class="field"><%= f.label :unit_price %><%= f.text_field :unit_price %></div>
  <div class="field"><%= f.label :quantity %><%= f.number_field :quantity %></div>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/order_items/edit.html.erb
<h1>EDIT ITEM</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path, id: 'back' %>

app/views/order_items/index.html.erb
<h1>ITEMS</h1>
<%= link_to 'New Item', new_order_item_path, class: 'button' %>
<table>
  <thead>
    <tr>
      <th class="col-md-1">Order</th>
      <th class="col-md-1">Item</th>
      <th class="col-md-8">Description</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td class="col-md-1"><%= order_item.order_id %></td>
        <td class="col-md-1"><%= link_to order_item.id, edit_order_item_path(order_item.id) %></td>
        <td class="col-md-8"><%= order_item.description %></td>
        <td><%= link_to 'X', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/order_items/new.html.erb
<h1>NEW ORDER ITEM</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path, id: 'back' %>

app/views/order_items/summary.html.erb
<% if params[:summary_button] %>
  <% @start_date = params[:start_date][:day] + "/" + params[:start_date][:month] + "/" + params[:start_date][:year] %>
  <% @end_date = params[:end_date][:day] + "/" + params[:end_date][:month] + "/" + params[:end_date][:year] %>
  <h2>SUMMARY FOR <%= @start_date %> TO <%= @end_date %></h2>
  <table>
    <tr>
      <th id='description'>Description</th>
      <th id='quantity'>Qty</th>
    </tr>
    <% @order_items.each do |o| %>
      <tr>
        <td class="col-md-11"><%= o[0] %></td>
        <td class="col-md-1"><%= o[1] %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div id="summary-form">
    <%= form_tag(summary_path, method: :get) do %>
      <p>
      Start: <%= select_date Date::today, :prefix => 'start_date' %> End: <%= select_date Date::today, :prefix => 'end_date' %>
      <%= submit_tag "Summarise", :name => 'summary_button' %>
      </p>
    <% end %>
</div>
<% end %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field"> <%= f.label 'Transaction:' %> <%= f.text_field :transaction_id, style: "display: inline;" %></div>
  <div class="field"> <%= f.label 'Date received:' %> <%= f.text_field :date_received, style: "display: inline;" %></div>
  <div class="field"> <%= f.label 'Email:' %> <%= f.text_field :paypal_email %> </div>
  <div class="field"> <%= f.label 'Payment Total:' %> <%= f.text_field :payment_total %></div>
  <div class="field"> <%= f.label 'Shipping Total:' %><%= f.text_field :shipping_total %></div>
  <div class="field"> <%= f.label 'Name:'%> <%= f.text_field :shipping_name %></div>
  <div class="field"> <%= f.label 'Address 1:' %><%= f.text_field :shipping_address1 %></div>
  <div class="field"> <%= f.label 'Address 2:' %><%= f.text_field :shipping_address2 %></div>
  <div class="field"> <%= f.label 'Address 3:' %><%= f.text_field :shipping_address3 %></div>
  <div class="field"> <%= f.label 'Address 4:' %><%= f.text_field :shipping_address4 %></div>
  <div class="field"> <%= f.label 'Address 5:' %><%= f.text_field :shipping_address5 %></div>
  <div class="field"> <%= f.label "Paypal ID:" %><%= f.text_field :paypal_id %> </div>
  
  <h2>ITEMS</h2>
  <table>
    <tr>
      <th id='description'>Description</th>
      <th id='item_number'>Item</th>
      <th id='unit_price'>Price</th>
      <th id='quantity'>Quantity</th>
    </tr>

  <%= f.fields_for :order_items do |g| %>
	  <fieldset>
	    <tr>
	      <td><%= g.text_field :description %>  </td>
        <td><%= g.text_field :item_number %>  </td>
        <td><%= g.text_field :unit_price %> </td>
        <td><%= g.number_field :quantity %> </td>
      </tr>
	  </fieldset>
  <% end %>
  </table>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>EDIT ORDER</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path, id: 'back' %>

app/views/orders/index.html.erb
<h1>ORDERS</h1>

<%= link_to 'New Order', new_order_path, class: 'button' %>
<%= submit_tag "Label" %>

<%= form_tag label_orders_path, method: :put do %>
<table>
  <thead>
    <tr>
      <th class="col-md-1"> </th>
      <th class="col-md-1">Order</th>
      <th class="col-md-4">Name</th>
      <th class="col-md-3">Email</th>
      <th class="col-md-2">Date received</th>
      <th class="col-md-1"> </th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td class="col-md-1"><%= check_box_tag "order_ids[]", order.id %></td>
        <td class="col-md-1"><%= link_to order.id, edit_order_path(order.id) %></td>
        <td class="col-md-4"><%= order.shipping_name %></td>
        <td class="col-md-3"><%= order.paypal_email %></td>
        <td class="col-md-2"><%= order.date_received.strftime("%Y%m%d") %></td>
        <td><%= link_to 'X', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/orders/label.html.erb
<%= form_tag label_orders_path, method: :get do %>
    <% @orders.each do |order|%>
        <table>
            <td><ul>
                <li> <%= order.shipping_name %></li>
                <li> <%= order.shipping_address1 %></li>
                <li> <%= order.shipping_address2 %></li>
                <li> <%= order.shipping_address3 %></li>
                <% if order.shipping_address4? %>
                    <li> <%= order.shipping_address4 %></li>
                <% else %>
                    <li> . </li>
                <% end %>
                <% if order.shipping_address5? %>
                    <li> <%= order.shipping_address5 %></li>
                <% else %>
                    <li> . </li>
                <% end %>
            </ul>
            </td>
            <td><ul>
                <li> Rolfe Deppe </li>
                <li> 16 Iron Street</li>
                <li> Muizenberg</li>
                <li> 7495 </li>
                <li> SOUTH AFRICA</li>
                <li> . </li>
            </ul>
            </td>
        </table>
    <% end %>
<% end %>

app/views/orders/mailing.html.erb
<h1>MAILING</h1>
<%= form_tag label_orders_path, method: :put do %>
<table>
  <thead>
    <tr>
      <th class="col-md-4">Name</th>
      <th class="col-md-3">Email</th>
      <th class="col-md-3">Country</th>
      <th class="col-md-2">Total Items</th>
    </tr>
  </thead>

  <tbody>
    <% @mailing.each do |mail| %>
      <tr>
        <td class="col-md-4"><%= mail.shipping_name %></td>
        <td class="col-md-3"><%= mail.paypal_email %></td>
        <% if mail.shipping_address5.present? %>
            <td class="col-md-3"><%= mail.shipping_address5 %></td>
        <% elsif mail.shipping_address4.present? %>
            <td class="col-md-3"><%= mail.shipping_address4 %></td>
        <% elsif mail.shipping_address3.present? %>
            <td class="col-md-3"><%= mail.shipping_address3 %></td>
        <% end %>
        <td class="col-md-2"><%= mail.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/orders/new.html.erb
<h1>NEW ORDER</h1>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% @description = [] %>
  <% @item_number = [] %>
  <% @unit_price = [] %>
  <% @quantity = [] %>
  
  <% if params[:paypal_button] %>
      <% inputString=(params["Paypal"]) %>
      <% if inputString.include? "Transaction ID:" %>
          <% a = inputString.index('Transaction ID:') + 15 %>
          <% b = a + 17 %>
          <% @transaction_id = inputString[a..b] %>
      <% end %>
      <% if inputString.include? "(" %>
          <% a = inputString.index('(') + 1 %>
          <% b = inputString.index(')') - 1 %>
          <% @paypal_email = inputString[a..b] %>
      <% end %>
      <% if inputString.include? "You received a payment of $" %>
          <% a = inputString.index('You received a payment of $') + 27 %>
          <% b = inputString.index(' USD from') - 1 %>
          <% @payment_total = inputString[a..b] %>
      <% end %>
      <% if inputString.include? "Shipping address" %>
        <% if inputString.include? "Shipping address - confirmed" %>
          <% a = inputString.index('Shipping address') + 30 %>
        <% else %>
          <% a = inputString.index('Shipping address') + 18 %>
        <% end %>
        <% b = inputString.index('Shipping details') - 1 %>
        <% lines = inputString[a..b].split("\n") %>
        <% @shipping_name = lines[0] %>
        <% @shipping_address1 = lines[1] %>
        <% @shipping_address2 = lines[2] %>
        <% @shipping_address3 = lines[3] %>
        <% @shipping_address4 = lines[4] %>
        <% @shipping_address5 = lines[5] %>
      <% end %>
      <% if inputString.include? "PayPal Email ID " %>
          <% a = inputString.index('PayPal Email ID ') + 15 %>
          <% b = a + 21 %>
          <% @paypal_id = inputString[a..b] %>
      <% end %>
      <% if inputString.include? "PayPal logo" %>
          <% a = inputString.index('PayPal logo') + 12 %>
          <% b = a + 10 %>
          <% @date_received = inputString[a..b].to_date %>
      <% end %>
      <% if inputString.include? "Shipping and handling" %>
          <% a = inputString.index('Shipping and handling') + 23 %>
          <% b = inputString.index('Insurance') - 6 %>
          <% @shipping_total = inputString[a..b].strip! %>
      <% end %>
      <% if inputString.include? "Amount" %>
        <% a = inputString.index('Amount') + 8 %>
        <% if inputString.include? "Subtotal" %>
          <% b = inputString.index('Subtotal') - 4 %>
        <% else %>
          <% b = inputString.index('Shipping and handling') - 4 %>
        <% end %>
        <% lines = inputString[a..b].split("\n") %>
        <% lines_count = lines.length %>
        <% even_index = 0 %>
        <% odd_index = 0 %>
        <% lines.each_with_index do |item,index| %>
          <% if index.even? %>
             <% @description[even_index] = lines[index] %>
             <% even_index += 1 %>
          <% else %>
            <% @item_number[odd_index] = item[6..17] %>
            <% b = item.index('USD') - 2 %>
            <% @unit_price[odd_index] = item[20..b] %>
            <% a = b + 6 %>
            <% b = item[a..37].index('$') - 2 + a %>
            <% @quantity[odd_index] = item[a..b] %>
            <% odd_index += 1 %>
          <% end %>
        <% end %>
      <% end %>
  <% else %>
    <div id="paypal-input"><%= text_area_tag "Paypal" %></div>
    <%= submit_tag 'Paypal', :name => 'paypal_button' %>
  <% end %>
  
  <div class="field"> <%= f.label 'Transaction:' %> <%= f.text_field :transaction_id, value: @transaction_id, style: "display: inline;" %></div>
  <div class="field"> <%= f.label 'Date received:' %> <%= f.text_field :date_received, value: @date_received, style: "display: inline;" %></div>
  <div class="field"> <%= f.label 'Email:' %> <%= f.text_field :paypal_email, value: @paypal_email %> </div>
  <div class="field"> <%= f.label 'Payment Total:' %> <%= f.text_field :payment_total, value: @payment_total %></div>
  <div class="field"> <%= f.label 'Shipping Total:' %><%= f.text_field :shipping_total, value: @shipping_total %></div>
  <div class="field"> <%= f.label 'Name:'%> <%= f.text_field :shipping_name, value: @shipping_name %></div>
  <div class="field"> <%= f.label 'Address 1:' %><%= f.text_field :shipping_address1, value: @shipping_address1 %></div>
  <div class="field"> <%= f.label 'Address 2:' %><%= f.text_field :shipping_address2, value: @shipping_address2 %></div>
  <div class="field"> <%= f.label 'Address 3:' %><%= f.text_field :shipping_address3, value: @shipping_address3 %></div>
  <div class="field"> <%= f.label 'Address 4:' %><%= f.text_field :shipping_address4, value: @shipping_address4 %></div>
  <div class="field"> <%= f.label 'Address 5:' %><%= f.text_field :shipping_address5, value: @shipping_address5 %></div>
  <div class="field"> <%= f.label "Paypal ID:" %><%= f.text_field :paypal_id, value: @paypal_id %> </div>


  <h2>ITEMS</h2>
  
  <table>
    <tr>
      <th id='description'>Description</th>
      <th id='item_number'>Item</th>
      <th id='unit_price'>Price</th>
      <th id='quantity'>Quantity</th>
    </tr>
  
  <% @counter = 0 %>
  <% @description.each do |order_item| %>
    <%= f.fields_for :order_items, @order.order_items.build do |g| %>
	    <fieldset>
	    <tr>
	      <td><%= g.text_field :description, value: @description[@counter] %>  </td>
        <td><%= g.text_field :item_number, value: @item_number[@counter] %>  </td>
        <td><%= g.text_field :unit_price, value: @unit_price[@counter] %> </td>
        <td><%= g.number_field :quantity, value: @quantity[@counter] %> </td>
        <%= g.hidden_field :user_id, value: current_user.id %> 
      </tr>
	    </fieldset>
	    <% @counter += 1 %>
    <% end %>
  <% end %>
  </table>
  <div class="actions"><%= f.submit %></div>

<% end %>

<%= link_to 'Back', orders_path, id: 'back' %>

app/views/orders/show.html.erb
<%= form_tag label_orders_path, method: :get do %>
    <%= @orders.each do |order|%>
        <ul>
            <li> order.shipping_name</li>
            <li> order.shipping_address1</li>
            <li> order.shipping_address2</li>
            <li> order.shipping_address3</li>
            <li> order.shipping_address4</li>
            <li> order.shipping_address5</li>
        </ul>
    <% end %>
<% end %>